sudo: required
services:
  - docker

before_install:
  - docker build -t jaymovaliya/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true jaymovaliya/react-test npm test -- --coverage

after_success:
  - docker build -t jaymovaliya/multi-client ./client
  - docker build -t jaymovaliya/multi-nginx ./nginx
  - docker build -t jaymovaliya/multi-server ./server
  - docker build -t jaymovaliya/multi-worker ./worker
  # Login to docker-cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push images to docker hub
  - docker push jaymovaliya/multi-client
  - docker push jaymovaliya/multi-nginx
  - docker push jaymovaliya/multi-server
  - docker push jaymovaliya/multi-worker
